[package]
name = "dtz-config"
version = "1.0.4"
edition.workspace = true
authors = ["jens@apimeister.com"]
description = "config crate for the DownToZero Cloud API"
license = "MIT OR Apache-2.0"
rust-version.workspace = true

[dependencies]
reqwest = { workspace = true }