[package]
name = "dtz-config"
version = "1.0.2"
edition = "2021"
authors = ["jens@apimeister.com"]
description = "config crate for the DownToZero Cloud API"
license = "MIT OR Apache-2.0"
rust-version = "1.83"

[dependencies]
reqwest = { workspace = true }