[package]
name = "dtz-identifier"
version = "1.5.0"
edition = "2021"
rust-version.workspace = true
authors = ["jens@apimeister.com"]
description = "identifier crate for the DownToZero Cloud API"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { workspace = true }
rand = { version = "0.9" }
